name: first work-flow

on:
  push:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - name: try
        run: echo "hello_world"
      - name: check
        uses: actions/checkout@v5.0.0
      - name: listing
        run: ls -la
